name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # Runs once a day at midnight UTC
  workflow_dispatch: # Allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream
        run: git remote add upstream https://github.com/sushi-dev55/sushitools-games-repo.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Merge upstream changes
        run: git merge upstream/main --allow-unrelated-histories || true

      - name: Push changes
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
